name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    tags:
      - 'v*'  # Nur f端r Versionstags (z.B. v1.0.0)

permissions:
  contents: read      # Erlaubt das Lesen von Repository-Inhalten
  security-events: write  # Erlaubt das Schreiben von Security-Analysen
  actions: read       # Erlaubt das Lesen von Actions
  packages: write     # Notwendig f端r Docker-Image Uploads
  id-token: write   # Erlaubt Zugriff auf GitHub Environments00

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_DATE: ${{ steps.set_date.outputs.CURRENT_DATE }}  # Definiere Output
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-0

      - name: Set CURRENT_DATE
        id: set_date
        run: |
            DATE=$(date +'%Y.%m.%d')
            echo "CURRENT_DATE=$DATE" >> $GITHUB_OUTPUT

      - name: Speichere CURRENT_DATE in Repository-Variable
        if: ${{ vars.CURRENT_DATE != steps.set_date.outputs.CURRENT_DATE }}  # Bedingung hinzuf端gen
        run: |
          curl -X PATCH \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/CURRENT_DATE \
          -d '{"value": "${{ steps.set_date.outputs.CURRENT_DATE }}"}'

  analyze:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set CURRENT_DATE from Build Output
        run: echo "CURRENT_DATE=${{ needs.build.outputs.CURRENT_DATE }}" >> $GITHUB_ENV

#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '23'
#
#      - name: Analyze with SonarCloud
#        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          args: >
#            -Dsonar.projectKey=Gentlecorp-Systems_gentlecorp-customer-service
#            -Dsonar.projectName=Customer-Service
#            -Dsonar.organization=gentlecorp-systems
#            -Dsonar.host.url=https://sonarcloud.io
#            -Dsonar.sources=./src/main/java
#            -Dsonar.exclusions=**/*.java
#            -Dsonar.branch.name=${{ github.ref_name }}

  camunda:
    name: Start Camunda Container
    runs-on: self-hosted
    if: github.actor == 'caleb-script'  # Nur wenn der Actor 'caleb-script' ist

    steps:
      - name: Start Camunda container (if not running)
        run: |
          if [ "$(docker ps -q -f name=zeebe)" ]; then
            echo "Camunda container is already running."
          else
            cd "${{ secrets.COMPOSE_PATH }}/camunda"
            docker compose up -d
          fi

  mongoDB:
   name: Start MongoDB Container
   runs-on: self-hosted
   if: github.actor == 'caleb-script'  # Nur wenn der Actor 'caleb-script' ist 
   steps:
     - name: Start MongoDB container (if not running)
       run: |
         if [ "$(docker ps -q -f name=mongodb)" ]; then
           echo "MongoDB container is already running."
         else
           cd "${{ secrets.COMPOSE_PATH }}/mongoDb"
           docker compose up -d
         fi

  test:
    name: Run Tests
    needs:
      - mongoDB
      - camunda
    runs-on: self-hosted
    if: github.actor == 'caleb-script'  # Nur wenn der Actor 'caleb-script' ist

    steps:
      - name: Print ref name
        run: echo "This workflow was triggered by ${{ github.ref_name }}"

      - name: Print actor (Collaborator)
        run: echo "The actor is ${{ github.actor }}"

      # 1. Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. `.env`-Datei mit Secrets erstellen
      - name: Create .env file
        run: |
          echo "KEYS_PATH=${{ secrets.KEYS_PATH }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "ACTIVE_PROFILE=${{ secrets.ACTIVE_PROFILE }}" >> .env
          echo "KC_SERVICE_HOST=${{ secrets.KC_SERVICE_HOST }}" >> .env
          echo "KC_SERVICE_PORT=${{ secrets.KC_SERVICE_PORT }}" >> .env
          echo "KC_SERVICE_REALM=${{ secrets.KC_SERVICE_REALM }}" >> .env
          echo "KC_SERVICE_CLIENT_ID=${{ secrets.KC_SERVICE_CLIENT_ID }}" >> .env
          echo "KC_SERVICE_SECRET=${{ secrets.KC_SERVICE_SECRET }}" >> .env
          echo "MONGODB_USER_NAME=${{ secrets.MONGODB_USER_NAME }}" >> .env
          echo "MONGODB_USER_PASSWORT=${{ secrets.MONGODB_USER_PASSWORT }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> .env
          echo "TEST_SERVER_PORT=${{ secrets.TEST_SERVER_PORT }}" >> .env
          echo "TEST_MONGODB_DATABASE=${{ secrets.TEST_MONGODB_DATABASE }}" >> .env

      # 3. Tests ausf端hren mit Code Coverage
      - name: Run Tests with Coverage
        run: ./gradlew clean build jacocoTestReport --no-daemon

      # 4. Testberichte speichern
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test

      # 5. Code Coverage Bericht hochladen
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@2d2cd3c094b82daf4a85daabc9d1aba59a7dde3c
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/html/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true

  compose_down:
    if: github.actor == 'caleb-script'
    name: Stop Docker Compose
    needs: test
    runs-on: self-hosted
    steps:
      - name: Stop Camunda container
        run: |
          cd "${{ secrets.COMPOSE_PATH }}"/camunda
          docker compose down

      - name: Stop MongoDB container
        run: |
          cd "${{ secrets.COMPOSE_PATH }}"/mongoDb
          docker compose down


  package:
    runs-on: ubuntu-latest
    needs: [analyze, test]
    if: github.actor == 'caleb-script'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Package Application
        run: ./gradlew bootJar --build-cache

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: customer-jar
          path: build/libs/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: [build, package]
    if: github.actor == 'caleb-script'
    env:
      CURRENT_DATE: ${{ needs.build.outputs.CURRENT_DATE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JAR File
        uses: actions/download-artifact@v4
        with:
          name: customer-jar
          path: build/libs

      - name: Set CURRENT_DATE from Build Output
        run: echo "${{ env.CURRENT_DATE }}"

      - name: Build Docker Image
        run: |
          docker build \
            -t gentlecorp-systems/customer:${{ env.CURRENT_DATE }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag gentlecorp-systems/customer:${{ env.CURRENT_DATE }} calebscript/customer:latest
          docker tag gentlecorp-systems/customer:${{ env.CURRENT_DATE }} calebscript/customer:${{ env.CURRENT_DATE }}

      - name: Push Docker Image
        run: |
          docker push calebscript/customer:${{ env.CURRENT_DATE }}
          docker push calebscript/customer:latest
