name: Weekly Docker Push to GHCR

on:
  schedule:
    - cron: '0 3 * * 1'  # Jeden Montag um 03:00 UTC
  workflow_dispatch:  # Manuelles Triggern möglich

permissions:
  contents: read
  packages: write  # Erlaubt das Hochladen von Images zu GHCR
  id-token: write

jobs:
  docker-push:
    runs-on: ubuntu-latest
    env:
      CURRENT_DATE: ${{ vars.CURRENT_DATE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Latest Docker Image from Docker Hub
        run: |
          docker pull calebscript/customer:${{ env.CURRENT_DATE }}

      - name: Tag Docker Image for GHCR
        run: |
          docker tag calebscript/customer:${{ env.CURRENT_DATE }} ghcr.io/gentlecorp-systems/customer:${{ env.CURRENT_DATE }}

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/gentlecorp-systems/customer:${{ env.CURRENT_DATE }}
