name: Create GitHub Release

on:
  push:
    tags:
      - "v*"  # Läuft nur bei neuen Tags wie v1.0.0

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automatisch generiertes Release für ${{ github.ref_name }}"
          draft: false
          prerelease: false
