name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    env:
      CURRENT_DATE: ${{ vars.CURRENT_DATE }}
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Resolve Gradle Dependencies
        run: ./gradlew dependencies

      - name: Run Snyk Code Test
        run: snyk code test --sarif > snyk-code.sarif
        continue-on-error: true

      - name: Run Snyk Monitor for Gradle
        if: github.event_name == 'push'
        run: snyk monitor --all-projects

      - name: Run Snyk IaC Test
        run: snyk iac test --report
        continue-on-error: true

      - name: Build a Docker Image
        run: docker build -t gentlecorp-systems/customer:${{ env.CURRENT_DATE }} .

      - name: Run Snyk Container Monitor
        run: snyk container monitor gentlecorp-systems/customer:${{ env.CURRENT_DATE }} --file=Dockerfile

      - name: Upload SARIF Report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
