name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Customer Tests
    runs-on: self-hosted # Nutze einen lokalen Runner

    steps:
      # 1. Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. `.env`-Datei mit Secrets erstellen
      - name: Create .env file
        run: |
          echo "KEYS_PATH=${{ secrets.KEYS_PATH }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env

      # 3. Tests ausführen mit Code Coverage
      - name: Run Tests with Coverage
        run: ./gradlew clean build jacocoTestReport --no-daemon

      # 4. Testberichte speichern
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test

      # 5. Code Coverage Bericht hochladen
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true
