name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Java Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK
      - name: Setup Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin' # Alternativen: zulu, adopt, etc.
          java-version: '23'      # Die Java-Version, die du nutzt
          cache: 'gradle'         # Gradle-Caching aktivieren

      # 3. Abhängigkeiten auflösen und Tests ausführen
      - name: Resolve dependencies and run tests
        run: ./gradlew clean build --no-daemon

      # 4. Testberichte speichern
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test

      # 5. Code Coverage Bericht hochladen (optional)
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html